# Generated by Django 4.2.6 on 2023-11-09 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0002_alter_mail_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Interview Attended', 'Interview Attended'), ('Rejected', 'Rejected'), ('Completed', 'Completed')], default='Pending', max_length=30),
        ),
    ]
