# Generated by Django 4.2.6 on 2023-11-12 11:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0003_mail_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='company',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mail',
            name='description',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+919999999999'. 10 digits allowed.", regex='^\\+?91?\\d{10}$')]),
        ),
        migrations.AddField(
            model_name='mail',
            name='jobtitle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mail',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mail',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+919999999999'. 10 digits allowed.", regex='^\\+?91?\\d{10}$')]),
        ),
        migrations.AddField(
            model_name='mail',
            name='package',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mail',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
