# Generated by Django 4.2.6 on 2023-11-12 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0004_mail_company_mail_description_mail_jobtitle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
